# Generated by Django 5.1.7 on 2025-03-16 20:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Escola', '0002_matricula'),
    ]

    operations = [
        migrations.RenameField(
            model_name='matricula',
            old_name='Curso',
            new_name='curso',
        ),
        migrations.RenameField(
            model_name='matricula',
            old_name='Estudante',
            new_name='estudante',
        ),
        migrations.RenameField(
            model_name='matricula',
            old_name='Periodo',
            new_name='periodo',
        ),
        migrations.AlterField(
            model_name='curso',
            name='codigo',
            field=models.CharField(max_length=10, unique=True, validators=[django.core.validators.MinLengthValidator(3)]),
        ),
        migrations.AlterField(
            model_name='estudante',
            name='cpf',
            field=models.CharField(max_length=11, unique=True),
        ),
    ]
